- name: Run CIS compliance playbook on RHEL7 machine
  hosts: "{{ vm_name }}"
  vars:
    rhel7cis_rule_3_4_3: false
  roles:
    - role: mindpointgroup.rhel7-cis
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | version_compare('7', '=')
